[package]
name = "geo-dd"
version = "0.1.0"
edition = "2024"

[dependencies]
differential-dataflow = "0.16.0"
itertools = "0.14.0"
plotters = "0.3"
proptest = "1.7.0"
serde = "1.0.219"
timely = "0.21.5"
